language: python

matrix:
  include:
    - python: "2.6"
      env: DJANGO=1.4 COVERAGE=YES
    - python: "2.6"
      env: DJANGO=1.4 YUBIKEY=YES

    - python: "2.7"
      env: DJANGO=1.7
    - python: "2.7"
      env: DJANGO=1.7 AUTH_USER_MODEL=tests.User
    - python: "3.4"
      env: DJANGO=1.7 COVERAGE=YES
    - python: "3.4"
      env: DJANGO=1.7 AUTH_USER_MODEL=tests.User YUBIKEY=YES COVERAGE=YES

    - python: "2.7"
      env: DJANGO=1.8
    - python: "2.7"
      env: DJANGO=1.8 AUTH_USER_MODEL=tests.User
    - python: "3.4"
      env: DJANGO=1.8 COVERAGE=YES
    - python: "3.4"
      env: DJANGO=1.8 AUTH_USER_MODEL=tests.User YUBIKEY=YES COVERAGE=YES

    - python: "3.4"
      env: FLAKE8=YES

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - if [[ $DJANGO ]]; then
        if [[ $DJANGO != 1.9* ]]; then
            pip install "django>=$DJANGO,<=$DJANGO.99";
        fi;
        if [[ $DJANGO == 1.8 ]]; then
            pip install django-formtools;
        fi;
        pip install -e .[Call,SMS];
    fi;
  - if [[ $COVERAGE == "YES" ]]; then pip install coveralls; fi;
  - if [[ $YUBIKEY == "YES" ]]; then pip install django-otp-yubikey; fi;
  - if [[ $FLAKE8 == "YES" ]]; then pip install flake8; fi;

script:
  - if [[ $DJANGO ]]; then
        if [[ $COVERAGE != "YES" ]]; then
            make test;
        else
            make coverage;
        fi;
    fi;
  - if [[ $FLAKE8 == "YES" ]]; then make flake8; fi;

after_success:
  - if [[ $COVERAGE == "YES" ]]; then coveralls; fi;
